dist: trusty
sudo: required
language: node_js
node_js:
  - 7
env:
  DOCKER_COMPOSE_VERSION: 1.11.2
addons:
  sources:
    - google-chrome
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java8-set-default
      - google-chrome-stable
      - couchdb
before_script:
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
after_success:
  - npm run build
  - npm run coveralls
